#!/usr/bin/env bash
# This script installs and does some basic configuration to an nginx service
apt-get update && apt -y upgrade
apt-get install -y nginx
/etc/init.d/nginx start
chown -R $USER:$USER /var/www/
chmod -R 755 /var/www
echo "Hello World" | sudo tee /var/www/html/index.html
/etc/init.d/nginx restart
