#!/usr/bin/env bash
# This script installs and does some basic configuration to an nginx service
sudo apt-get update && sudo apt -y upgrade
sudo apt-get install -y nginx
sudo /etc/init.d/nginx start
# sudo chown -R $USER:$USER /var/www/
# sudo chmod -R 755 /var/www
sudo echo "Hello World" | sudo tee /var/www/html/index.html
sudo /etc/init.d/nginx restart
