#!/usr/bin/env bash
# This script installs nginx on web-01 server
# This script uses a 301 redirection to nyancat
# https://www.youtube.com/watch?v=QH2-TGUlwu4

find="^\tlocation / {"
replace301="\tlocation /redirect_me {\n\t\treturn 301 \@scheme://youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"
replace404="\terror_page 404 /error404.html;\n\n\tlocation / {"

sudo apt-get -y update
sudo apt-get install -y nginx
sudo rm /var/www/html/*.html
sudo echo "Hello World" | sudo tee /var/www/html/index.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
sudo sed -i "s|$find|$replace301|" /etc/nginx/sites-available/default
sudo sed -i "s|$find|$replace404|" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
