#!/usr/bin/env bash
# This script is an endless loop which prints "to infinity and beyond" every 2s
indatrap_quit () {
    rm -rf /var/run/myscript.pid
    kill -9 "$$"
}
indatrap_int () {
    echo "Y U no love me?!"
}
indatrap_term () {
    echo "I hate the kill command"
    rm -rf /var/run/myscript.pid
    kill -9 "$$"
}
trap 'indatrap_term' TERM
trap 'indatrap_int' INT
trap 'indatrap_quit' QUIT

echo "$$"  > /var/run/myscript.pid

while true
do echo "To infinity and beyond"
   sleep 2
done
