#!/usr/bin/env bash
#This script tells a story based on the contents of /etc/passwd
while IFS=":" read -r u x uid gid usrinf home shell
do 
    printf "The user %s is part of the %s gang, lives in %s and rides %s. %s's place is protected by the passcode %s, more info about the user here: %s\n" "$u" "$gid" "$home" "$shell" "$uid" "$x" "$usrinf"
done < /etc/passwd
