#!/usr/bin/env bash
# Install nginx and add custom header to server

sudo apt update && sudo apt -y upgrade
sudo apt-get install -y nginx

mkdir -p /var/www/html
sudo touch /var/www/html/index.html
echo "Hello World" > /var/www/html/index.html
sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" > sudo var/www/html/404.html

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://oktechguru.com;
    }
    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > sudo /etc/nginx/sites-available/default
